model_path: "checkpoints/checkpoint_sft_filtered_epoch_5"
data_train_path: "data/MATH/train.jsonl"
data_eval_path: "data/MATH/validation.jsonl"
prompt_template_path: "cs336_alignment/prompts/r1_zero.prompt"
train_device: "cuda:0"       
eval_device: "cuda:1" 

log_dir: "./logs"            
save_dir: "./checkpoints"    

n_grpo_steps: 200                    
train_batch_size: 256                
gradient_accumulation_steps: 128     
rollout_batch_size: 256              
group_size: 8                        
n_grpo_iterations: 1                 

lr: 1e-6                            
seed: 42
lr_scheduler: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1

reward_type: "r1_zero"               
normalize_std: true                  
loss_type: "grpo_clip" 
cliprange: 0.2                       
